module.exports = {
  USER_MODEL_NAME: "user",
  PRODUCT_MODEL_NAME: "product",
  RETAILER_MODEL_NAME: "retailer",
  WHOLESALER_MODEL_NAME: "wholesaler",
  CART_MODEL_NAME: "cart",
  CART_ITEMS: "cart_item",
  ORDER_MODEL_NAME: "order",
  ORDERED_ITEMS: "ordered_item",
  ADDRESS: "address",
  ORDER_ADDRESS: "orderAddress",
  INVOICE_MODEL_NAME: "invoice",
  INVOICED_ITEMS: "invoiced_item",
  PARTIAL_INVOICE_TRACKING: "partialInvoiceTracking",
  BACKORDER_MODEL_NAME: "backOrder",
  BACKORDER_ITEMS: "backorder_item",
  PRODUCT_TYPE_MODEL_NAME: "productType",
  STATES_MODEL_NAME: "state",
  COUNTRY_MODEL_NAME: "country",
  CATEGORY_MODEL_NAME: "category",
  FILE_MASTER_PRODUCT_MODEL_NAME: "file_master_products",
  WHOLESALER_INVENTORY_MODEL_NAME: "wholesalerInventory",
  RETURN_MODEL_NAME: "return",
  RETURN_ITEMS: "return_item",
  RETURN_ITEMS_IMAGES: "return_item_image",
  TERMS_AND_CONDITIONS: "termsAndConditions",
  CONTACT: "contactUs",
};
